In [1]:
# Import Dependencies
import pandas as pd
import numpy as np
from config import api_key
import requests
from pprint import pprint

In [2]:
# Define API base url and targetted years of movies data
url1 = "https://api.themoviedb.org/3/discover/movie?"
year_data = [2015,2016,2017,2018]

In [3]:
# Call the API url , Check for response and print the response whether the data is available or not
# store the repsonse as JSON data
movies_id_data = []
page_num = 1

for year in year_data:
    
    for page_num in range(1,11):
        response = requests.get(f"{url1}api_key={api_key}&primary_release_year={year}&page={page_num}")
        print(response.url)
        movies = response.json()
       #movies_data.append(response.json())
        page_num = page_num + 1
               
    
        for movie in movies['results']:
            movies_id_data.append(movie['id'])
    
    
#print(movies_id_data)
#pprint(movies_data_list)

https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2015&page=1
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2015&page=2
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2015&page=3
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2015&page=4
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2015&page=5
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2015&page=6
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2015&page=7
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2015&page=8
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2015&page=9
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2015&page=10
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2016&page=1
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2016&page=2
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2016&page=3
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2016&page=4
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2016&page=5
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2016&page=6
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2016&page=7
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2016&page=8
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2016&page=9
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2016&page=10
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2017&page=1
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2017&page=2
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2017&page=3
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2017&page=4
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2017&page=5
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2017&page=6
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2017&page=7
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2017&page=8
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2017&page=9
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2017&page=10
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2018&page=1
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2018&page=2
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2018&page=3
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2018&page=4
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2018&page=5
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2018&page=6
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2018&page=7
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2018&page=8
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2018&page=9
https://api.themoviedb.org/3/discover/movie?api_key=f63b434c2eae10c869016441dc039f7b&primary_release_year=2018&page=10

In [4]:
print(len(movies_id_data))

800

In [5]:
# Using movie id list call the TMDb API for more movie information
url2 = "https://api.themoviedb.org/3/movie/"
movies_details = []

for mve_id in movies_id_data:
    
    response2 = requests.get(f"{url2}{mve_id}?api_key={api_key}")
    #print(response2.url)
    movies_details.append(response2.json())
        
#pprint(movies_details)

In [6]:
movie_id1 = []
movie_title = []
budget = []
revenue = []
release_date = []
genre = []
production_comp = []
tag_line = []

def write_null(v1):
    if v1 == movie_id1:
        movie_id1.append("NaN")
    if v1 == movie_title:
        movie_title.append("NaN")
    if v1 == budget:
        budget.append("NaN")
    if v1 == revenue:
        revenue.append("NaN")
    if v1 == genre:
        genre.append("NaN")
    if v1 == tag_line:
        tag_line.append("NaN")
    if v1 == production_comp:
        production_comp.append("NaN")
    if v1 == release_date:
        release_date.append("NaN")
    
for detail in movies_details:
      
    try:
        movie_id1.append(detail["id"])
    except:
        write_null(movie_id1)
    try:
        movie_title.append(detail["title"])
    except:
        write_null(movie_title)
    try:
        budget.append(detail["budget"])
    except:
        write_null(budget)
    try:
        revenue.append(detail["revenue"])
    except:
        write_null(revenue)
    try:
        genre.append(detail["genres"][0]["name"])
    except:
        write_null(genre)
    try:
        tag_line.append(detail["tagline"])
    except:
        write_null(tag_line)  
    try:
        production_comp.append(detail["production_companies"][0]["name"])
    except:
        write_null(production_comp)
    try:
        release_date.append(detail["release_date"])
    except:
        write_null(release_date)

In [7]:
print(len(movie_id1))
print(len(movie_title))
print(len(budget))
print(len(revenue))
print(len(genre))
print(len(tag_line))
print(len(release_date))

800
800
800
800
800
800
800

In [8]:
movie_df_frame = pd.DataFrame({"Movie ID":movie_id1,"Title": movie_title, "Budget":budget,"Tagline":tag_line,
                               "Revenue": revenue, "Genre": genre, "Production Company": production_comp, "Release Date": release_date},
                                 columns = ["Title", "Movie ID","Genre","Production Company","Budget", "Revenue", "Tagline", "Release Date"])
movie_df_frame.to_csv("santhosh.csv", index =False)
movie_df_frame

,Title,Movie ID,Genre,Production Company,Budget,Revenue,Tagline,Release Date
0,Avengers: Age of Ultron,99861,Action,Prime Focus,280000000,1405403694,A New Age Has Come.,2015-04-22
1,Terminator Genisys,87101,Science Fiction,Skydance Media,155000000,440603537,Reset the future,2015-06-23
2,San Andreas,254128,Action,New Line Cinema,110000000,470490832,"A rescue pilot survived an earthquake, this is...",2015-05-27
3,Cinderella,150689,Romance,Walt Disney Pictures,95000000,543514353,Midnight is just the beginning.,2015-03-12
4,Mad Max: Fury Road,76341,Action,Village Roadshow Pictures,150000000,378858340,What a Lovely Day.,2015-05-13
5,Star Wars: The Force Awakens,140607,Action,Truenorth Productions,245000000,2068223624,Every generation has a story.,2015-12-15
6,Spectre,206647,Action,Danjaq,245000000,880674609,A Plan No One Escapes,2015-10-26
7,Inside Out,150540,Drama,Pixar,175000000,857611174,Meet the little voices inside your head.,2015-06-09
8,Insurgent,262500,Action,Summit Entertainment,110000000,295238201,One Choice Can Destroy You,2015-03-18
9,Jupiter Ascending,76757,Science Fiction,Anarchos Productions,176000003,183987723,Expand your universe.,2015-02-04
10,Chappie,198184,Crime,Columbia Pictures,49000000,104399548,I am consciousness. I am alive. I am Chappie.,2015-03-04
11,Ant-Man,102899,Science Fiction,Marvel Studios,130000000,519311965,Heroes don't get any bigger.,2015-07-14
12,Tomorrowland,158852,Adventure,Babieka,190000000,209154322,Imagine a world where nothing is impossible.,2015-05-19
13,Maze Runner: The Scorch Trials,294254,Action,Temple Hill Entertainment,61000000,311256926,The Maze Was Just the Beginning.,2015-09-09
14,Everest,253412,Adventure,Cross Creek Pictures,55000000,203427584,The Storm Awaits.,2015-09-10
15,Mission: Impossible - Rogue Nation,177677,Action,Paramount,150000000,682330139,Desperate Times. Desperate Measures.,2015-07-23
16,Fifty Shades of Grey,216015,Drama,Trigger Street Productions,40000000,571006128,Are you curious?,2015-02-11
17,Furious 7,168259,Action,Abu Dhabi Film Commission,190000000,1506249360,Vengeance Hits Home,2015-04-01
18,The Walk,285783,Adventure,TriStar Pictures,35000000,61181942,Dream High.,2015-09-30
19,Ex Machina,264660,Drama,A24,15000000,36869414,There is nothing more human than the will to s...,2015-01-21
20,Southpaw,307081,Action,Fuqua Films,30000000,91709827,Believe in Hope.,2015-06-15
21,Jurassic World,135397,Action,Fuji Television Network,150000000,1513528810,The park is open.,2015-06-09
22,Bridge of Spies,296098,Thriller,TSG Entertainment,40000000,165478348,"In the shadow of war, one man showed the world...",2015-10-15
23,Sicario,273481,Action,Lionsgate,30000000,84025816,The border is just another line to cross.,2015-09-17
24,Creed,312221,Drama,Chartoff Winkler Productions,37000000,173567581,Your legacy is more than a name,2015-11-25
25,Female War: A Nasty Deal,399905,Drama,NaN,0,0,,2015-09-27
26,Room,264644,Drama,Elevation Pictures,6000000,35401758,Love knows no boundaries,2015-10-16
27,The Man from U.N.C.L.E.,203801,Comedy,Wigram Productions,75000000,108145109,Saving the world never goes out of style.,2015-08-13
28,The Big Short,318846,Comedy,Plan B Entertainment,28000000,133346506,This is a true story.,2015-12-11
29,Kingsman: The Secret Service,207703,Crime,TSG Entertainment,81000000,414351546,Manners maketh man.,2015-01-24
...,...,...,...,...,...,...,...,...
770,The Miracle Season,425373,Drama,NaN,0,0,,2018-04-13
771,Marillion: All One Tonight - Live At The Royal...,511115,Music,NaN,0,0,,2018-04-02
772,Rangasthalam,461126,Action,Konidela Production Company,7800000,0,,2018-03-29
773,Marty,513131,NaN,NaN,0,0,,2018-04-08
774,Chappaquiddick,432301,Drama,Apex Entertainment,0,0,,2018-04-06
775,Ice,440630,Comedy,Art Pictures Studio,2500000,0,,2018-02-14
776,Allure,467916,Thriller,micro_scope,0,0,,2018-03-16
777,Ocean's 8,402900,Adventure,Village Roadshow Pictures,0,0,Every con has its pros,2018-06-07
778,Tre Maison Dasan,511799,Documentary,NaN,0,0,,2018-04-08
779,Capturing the Flag,514733,Documentary,NaN,0,0,,2018-04-08
780,Little Bitches,387773,Comedy,Sony Pictures,0,0,Best Friends for Never,2018-01-23
781,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
782,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
783,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
785,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
786,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
787,The First Purge,442249,Action,Platinum Dunes,0,0,,2018-07-04
788,The Leisure Seeker,449749,Drama,Rai Cinema,0,0,,2018-01-03
789,Sgt. Stubby: An American Hero,433694,NaN,NaN,0,0,,2018-04-13
790,Super Troopers 2,50022,Comedy,Broken Lizard Industries,5000000,0,The Time is Meow,2018-04-20
791,Andre the Giant,446663,Documentary,HBO Sports,0,0,Even bigger than you imagined,2018-04-10
792,First Reformed,458737,Thriller,Arclight Films,0,0,,2018-04-04
793,49 Mile Scenic Drive,513129,NaN,NaN,0,0,,2018-04-08
794,Les Tuche 3,424619,Comedy,Pathé,0,0,,2018-01-31
795,Bent,505579,Thriller,NaN,0,0,,2018-03-09
796,Fantastic Beasts: The Crimes of Grindelwald,338952,Drama,Warner Bros. Pictures,0,0,,2018-11-08
797,Portugal Não Está à Venda,510068,Comedy,NaN,0,0,,2018-04-01
798,Compulsion,368182,Thriller,NaN,0,0,There are no rules,2018-03-15
799,#TemanTapiMenikah,503352,Comedy,Falcon Pictures,0,0,,2018-03-29